### ISSUE TITLE
Error when executing grepsearch command without arguments

### ISSUE THREAD

**Issue by ghost** [gaenseklein/grepsearch#1]
When I try to run the grepsearch command without arguments, an error is thrown and the editor closes.

The following error is displayed:

```sh
Lua API error: grepsearch:141: attempt to call a non-function object
stack traceback:
	grepsearch:141: in main chunk
	[G]: ?
```

**Comment by gaenseklein** [comment]
thx for the feedback. it is fixed now in current main (function was local)
